create schema blog;

-- CRIANDO MINHAS TABELAS PELO CLIPBOADR DO DIAGRAMA!!!!

-- MySQL Script generated by MySQL Workbench
-- Thu Nov  3 10:02:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `emailUser` VARCHAR(50) NOT NULL,
  `passwordUser` VARCHAR(15) NOT NULL,
  `typeUser` CHAR(3) NOT NULL,
  PRIMARY KEY (`idUsers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`posts` (
  `idPosts` INT NOT NULL AUTO_INCREMENT,
  `titlePost` VARCHAR(50) NOT NULL,
  `textPost` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`idPosts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comments` (
  `idComments` INT NOT NULL AUTO_INCREMENT,
  `textComment` VARCHAR(200) NOT NULL,
  `validateComment` CHAR(1) NOT NULL,
  `users_idUsers` INT NOT NULL,
  `posts_idPosts` INT NOT NULL,
  PRIMARY KEY (`idComments`),
  INDEX `fk_comments_users_idx` (`users_idUsers` ASC) VISIBLE,
  INDEX `fk_comments_posts1_idx` (`posts_idPosts` ASC) VISIBLE,
  CONSTRAINT `fk_comments_users`
    FOREIGN KEY (`users_idUsers`)
    REFERENCES `mydb`.`users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_posts1`
    FOREIGN KEY (`posts_idPosts`)
    REFERENCES `mydb`.`posts` (`idPosts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
